### ISSUE TITLE
Confusion about implement of KL and KLUP

### ISSUE THREAD

**Issue by JaireYu** [atuannguyen/KL#1]
Hi, Atuannguyen! Congratulations on great ICLR paper! 

When reading your code, I feed kind of confused. In loss.py and algorithms.py, there are `kl_upper`, `kl_lower` functions and `KLUP` class. However, `KLUP` is not in your ALGORITHM list. 

I wonder if `KLUP` and `kl_upper` also work well for Domain Adaptation? I would prefer to use `kl_upper` function because I am not working with re-parameter trick. 

Seeking for your reply!

**Comment by atuannguyen** [comment]
Hi,

I believe KLUP is a model I was testing in a preliminary state. Basically, I was implementing an upper bound and a lower bound of the KL between 2 mixtures of gaussian as in this [paper](https://os.zhdk.cloud.switch.ch/tind-tmp-epfl/fb229e45-27d1-4a2a-ad22-71e63fa10324?response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27durrieuThiranKelly_kldiv_icassp2012_R1.pdf&response-content-type=application%2Fpdf&AWSAccessKeyId=ded3589a13b4450889b2f728d54861a6&Expires=1657753873&Signature=CDr7zMYxBtsesfIjLpUGZAeFxIA%3D), so that we don't have to estimate the KL via MC sampling. If I recall correctly, it performs pretty well for the RotatedMNIST experiments. I haven't tested it extensively though, you are welcome to test it!

Let me know if you have further questions.

**Comment by JaireYu** [comment]
Thank you for your quick reply! I will try KLUP model in my work.
